#!/usr/bin/env python3
"""
Script to update TTL files with subject and object authority information from JSON mappings.

This script reads a mapping JSON file (generated by query_predicate_authorities.py)
and enriches the corresponding TTL file by adding sbm:authorityRelation entries
to each propertyPartition, documenting which authorities appear in subjects and objects.

Uses rdflib to properly handle RDF parsing, manipulation, and serialization.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
from collections import Counter
from rdflib import Graph, Namespace, URIRef, Literal, BNode
from rdflib.namespace import RDF, XSD


# Define namespaces
VOID = Namespace("http://rdfs.org/ns/void#")
SBM = Namespace("http://sparqlbuilder.org/2015/09/rdf-metadata-schema#")
SD = Namespace("http://www.w3.org/ns/sparql-service-description#")


def load_mappings(json_file: Path) -> Dict:
    """Load the mappings JSON file."""
    with open(json_file, 'r') as f:
        return json.load(f)


def extract_authorities_from_mappings(mappings: Dict, predicate: str) -> Tuple[List[Dict], List[Dict]]:
    """
    Extract subject and object authorities for a given predicate from the mappings.
    
    Returns a tuple of (subject_authorities, object_authorities) lists,
    where each list contains dicts with 'authority' and 'count' keys.
    
    Aggregates counts from all graphs for the predicate.
    """
    for result in mappings.get("results", []):
        if result.get("predicate") == predicate:
            graphs = result.get("graphs", {})

            subject_counter = Counter()
            object_counter = Counter()

            for graph_data in graphs.values():
                for auth_info in graph_data.get("subject_authorities", []):
                    authority = auth_info.get("authority")
                    count = int(auth_info.get("count", 0) or 0)
                    if authority:
                        subject_counter[authority] += count

                for auth_info in graph_data.get("object_authorities", []):
                    authority = auth_info.get("authority")
                    count = int(auth_info.get("count", 0) or 0)
                    if authority:
                        object_counter[authority] += count

            subject_auths = [
                {"authority": auth, "count": count}
                for auth, count in subject_counter.most_common()
            ]
            object_auths = [
                {"authority": auth, "count": count}
                for auth, count in object_counter.most_common()
            ]
            return subject_auths, object_auths
    
    return [], []


def build_partition_index(g: Graph) -> Dict[str, URIRef | BNode]:
    """Build predicate -> partition node index from existing TTL content."""
    partition_index: Dict[str, URIRef | BNode] = {}

    # Standard structure: dataset void:propertyPartition partition .
    for partition in g.objects(None, VOID.propertyPartition):
        prop = g.value(partition, VOID.property)
        if isinstance(prop, URIRef):
            partition_index[str(prop)] = partition

    # Fallback: any node that directly has void:property
    for partition in g.subjects(VOID.property, None):
        prop = g.value(partition, VOID.property)
        if isinstance(prop, URIRef) and str(prop) not in partition_index:
            partition_index[str(prop)] = partition

    return partition_index


def find_or_create_dataset_node(g: Graph) -> URIRef | BNode:
    """Find a dataset node to attach new property partitions to, or create one."""
    dataset = next(g.subjects(VOID.propertyPartition, None), None)
    if dataset is not None:
        return dataset

    endpoint_subject = next(g.subjects(SD.endpoint, None), None)
    if endpoint_subject is not None:
        return endpoint_subject

    dataset = BNode()
    g.add((dataset, RDF.type, VOID.Dataset))
    return dataset


def ensure_partition_for_predicate(
    g: Graph,
    dataset_node: URIRef | BNode,
    partition_index: Dict[str, URIRef | BNode],
    predicate: str,
) -> Tuple[URIRef | BNode, bool]:
    """Return partition for predicate; create a minimal one if missing."""
    existing_partition = partition_index.get(predicate)
    if existing_partition is not None:
        return existing_partition, False

    partition = BNode()
    predicate_uri = URIRef(predicate)
    g.add((dataset_node, VOID.propertyPartition, partition))
    g.add((partition, RDF.type, VOID.Dataset))
    g.add((partition, VOID.property, predicate_uri))
    partition_index[predicate] = partition
    return partition, True


def get_partition_total_triples(mapping_result: Dict) -> int:
    """Get the best available triple count for a predicate partition."""
    total_from_queries = 0

    graphs = mapping_result.get("graphs", {})
    if isinstance(graphs, dict):
        for graph_data in graphs.values():
            if not isinstance(graph_data, dict):
                continue
            try:
                total_from_queries += int(graph_data.get("total_results", 0) or 0)
            except (TypeError, ValueError):
                continue

    if total_from_queries > 0:
        return total_from_queries

    try:
        return int(mapping_result.get("total_triples", 0) or 0)
    except (TypeError, ValueError):
        return 0


def ensure_partition_triple_count(
    g: Graph,
    partition: URIRef | BNode,
    triple_count: int,
) -> bool:
    """Add void:triples to a propertyPartition when it is missing."""
    if triple_count <= 0:
        return False

    if g.value(partition, VOID.triples) is not None:
        return False

    g.add((partition, VOID.triples, Literal(triple_count, datatype=XSD.long)))
    return True


def authority_relation_exists(
    g: Graph,
    partition: URIRef | BNode,
    relation_type: URIRef,
    authority: str,
) -> bool:
    """Check whether an authorityRelation already exists for partition/type/authority."""
    authority_uri = URIRef(authority)
    for auth_rel in g.objects(partition, SBM.authorityRelation):
        existing_type = g.value(auth_rel, SBM.relationType)
        existing_auth = g.value(auth_rel, SBM.authority)
        if existing_type == relation_type and existing_auth == authority_uri:
            return True
    return False


def filter_authorities(authorities: List[Dict]) -> List[Dict]:
    """Keep only concrete authorities that can be materialized in TTL."""
    filtered: List[Dict] = []
    for auth_info in authorities:
        authority = auth_info.get("authority", "")
        if not authority or authority == "any":
            continue
        filtered.append(
            {
                "authority": authority,
                "count": int(auth_info.get("count", 0) or 0),
            }
        )
    return filtered


def has_partition_updates(
    subject_auths: List[Dict],
    object_auths: List[Dict],
    partition_total_triples: int,
) -> bool:
    """Return True when a predicate has material updates worth writing."""
    return bool(subject_auths or object_auths or partition_total_triples > 0)


def iter_ttl_files(ttl_dir: Path) -> Iterable[Path]:
    """Yield TTL files from a folder in a stable order."""
    yield from sorted(path for path in ttl_dir.glob("*.ttl") if path.is_file())


def build_output_path(ttl_file: Path, suffix: str) -> Path:
    """Build output path next to the source TTL file using a suffix."""
    return ttl_file.with_name(f"{ttl_file.stem}{suffix}{ttl_file.suffix}")


def candidate_json_stems(ttl_file: Path) -> List[str]:
    """Return candidate JSON stems for a TTL file, including update-suffix fallbacks."""
    stem = ttl_file.stem
    stems = [stem]

    for suffix in ("_updated", "_update"):
        if stem.endswith(suffix):
            stems.append(stem[: -len(suffix)])

    return list(dict.fromkeys(candidate for candidate in stems if candidate))


def find_json_mapping_for_ttl(ttl_file: Path, json_dir: Path) -> Optional[Path]:
    """Resolve the JSON mapping partner for a TTL file by filename stem."""
    for stem in candidate_json_stems(ttl_file):
        candidate = json_dir / f"{stem}.json"
        if candidate.exists():
            return candidate
    return None


def update_ttl_directory(ttl_dir: Path, json_dir: Path, suffix: str = "_updated") -> bool:
    """Update all TTL files in a folder using stem-matched JSON mapping files."""
    if not ttl_dir.exists() or not ttl_dir.is_dir():
        print(f"Error: TTL directory not found: {ttl_dir}")
        return False

    if not json_dir.exists() or not json_dir.is_dir():
        print(f"Error: JSON directory not found: {json_dir}")
        return False

    ttl_files = list(iter_ttl_files(ttl_dir))
    if not ttl_files:
        print(f"No TTL files found in: {ttl_dir}")
        return False

    print(f"Discovered {len(ttl_files)} TTL files in: {ttl_dir}")

    processed = 0
    updated = 0
    skipped = 0
    failures = 0

    for ttl_file in ttl_files:
        processed += 1
        json_file = find_json_mapping_for_ttl(ttl_file, json_dir)
        if json_file is None:
            skipped += 1
            print(
                f"Skipping {ttl_file.name}: matching JSON mapping not found for stems {candidate_json_stems(ttl_file)}"
            )
            continue

        output_file = build_output_path(ttl_file, suffix)
        print("-" * 80)
        print(f"Batch item {processed}/{len(ttl_files)}")
        print(f"TTL:    {ttl_file}")
        print(f"JSON:   {json_file}")
        print(f"Output: {output_file}")

        if update_ttl_file(ttl_file, json_file, output_file):
            updated += 1
        else:
            failures += 1

    print("=" * 80)
    print("Batch update summary")
    print(f"  TTL files discovered: {len(ttl_files)}")
    print(f"  Files processed:      {processed}")
    print(f"  Files updated:        {updated}")
    print(f"  Files skipped:        {skipped}")
    print(f"  Files failed:         {failures}")

    return failures == 0 and updated > 0


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for single-file and batch update modes."""
    parser = argparse.ArgumentParser(
        description=(
            "Enrich TTL property partitions with authority metadata from JSON mappings. "
            "Supports single-file mode and folder-wide batch mode."
        )
    )
    parser.add_argument(
        "ttl_file",
        nargs="?",
        help="Path to a TTL file to update in single-file mode.",
    )
    parser.add_argument(
        "json_mapping_file",
        nargs="?",
        help="Path to the JSON mappings file paired with ttl_file in single-file mode.",
    )
    parser.add_argument(
        "output_file",
        nargs="?",
        help="Optional output path for single-file mode. Defaults to in-place overwrite.",
    )
    parser.add_argument(
        "--ttl-dir",
        type=Path,
        help="Folder containing TTL files to update in batch mode.",
    )
    parser.add_argument(
        "--json-dir",
        type=Path,
        help="Folder containing JSON mapping files matched to TTL files by filename stem.",
    )
    parser.add_argument(
        "--suffix",
        default="_updated",
        help="Suffix for batch output files written next to each source TTL file.",
    )

    args = parser.parse_args()

    single_mode = args.ttl_file is not None and args.json_mapping_file is not None
    batch_mode = args.ttl_dir is not None or args.json_dir is not None

    if single_mode and batch_mode:
        parser.error("Choose either single-file mode or folder batch mode, not both.")

    if batch_mode:
        if args.ttl_dir is None or args.json_dir is None:
            parser.error("Batch mode requires both --ttl-dir and --json-dir.")
    else:
        if not single_mode:
            parser.error(
                "Single-file mode requires <ttl_file> and <json_mapping_file>, or use --ttl-dir with --json-dir."
            )

    return args


def update_ttl_file(ttl_file: Path, json_file: Path, output_file: Optional[Path] = None):
    """
    Main function to update TTL file with authority information using rdflib.
    """
    if not ttl_file.exists():
        print(f"Error: TTL file not found: {ttl_file}")
        return False
    
    if not json_file.exists():
        print(f"Error: JSON mapping file not found: {json_file}")
        return False
    
    if output_file is None:
        output_file = ttl_file
    
    print(f"Loading mappings from: {json_file}")
    mappings = load_mappings(json_file)
    
    print(f"Loading TTL file: {ttl_file}")
    g = Graph()
    g.bind("void", VOID)
    g.bind("sbm", SBM)
    g.bind("sd", SD)
    
    try:
        g.parse(ttl_file, format="turtle")
    except Exception as e:
        print(f"Error parsing TTL file: {e}")
        return False
    
    print(f"Processing RDF graph and adding authority relations...")

    partition_index = build_partition_index(g)
    dataset_node = find_or_create_dataset_node(g)
    print(f"Found {len(partition_index)} existing propertyPartitions")

    added_count = 0
    created_partitions = 0
    added_partition_triple_counts = 0
    skipped_predicates = 0

    mapping_results = mappings.get("results", [])
    for mapping_result in mapping_results:
        predicate_str = mapping_result.get("predicate")
        if not predicate_str:
            continue

        subject_auths, object_auths = extract_authorities_from_mappings(mappings, predicate_str)
        subject_auths = filter_authorities(subject_auths)
        object_auths = filter_authorities(object_auths)
        partition_total_triples = get_partition_total_triples(mapping_result)
        existing_partition = partition_index.get(predicate_str)
        if existing_partition is None and not has_partition_updates(
            subject_auths,
            object_auths,
            partition_total_triples,
        ):
            skipped_predicates += 1
            continue

        partition, was_created = ensure_partition_for_predicate(
            g,
            dataset_node,
            partition_index,
            predicate_str,
        )

        if was_created:
            created_partitions += 1
            print(f"  Created propertyPartition for missing predicate: {predicate_str}")

        if ensure_partition_triple_count(g, partition, partition_total_triples):
            added_partition_triple_counts += 1
            print(
                f"  Added void:triples={partition_total_triples} to propertyPartition: {predicate_str}"
            )

        if subject_auths or object_auths:
            print(f"  Processing predicate: {predicate_str}")

            # Add authorityRelation for subject authorities, including predicates with literal objects.
            for auth_info in subject_auths:
                authority = auth_info["authority"]
                count = auth_info["count"]
                if authority_relation_exists(g, partition, SBM.Subject, authority):
                    continue

                auth_rel = BNode()
                g.add((auth_rel, RDF.type, SBM.AuthorityRelation))
                g.add((auth_rel, SBM.authority, URIRef(authority)))
                g.add((auth_rel, SBM.relationType, SBM.Subject))
                g.add((auth_rel, SBM.authorityCount, Literal(count, datatype=XSD.long)))
                g.add((partition, SBM.authorityRelation, auth_rel))
                added_count += 1

            # Add object authorities only when they are concrete IRIs.
            for auth_info in object_auths:
                authority = auth_info["authority"]
                count = auth_info["count"]
                if authority_relation_exists(g, partition, SBM.Object, authority):
                    continue

                auth_rel = BNode()
                g.add((auth_rel, RDF.type, SBM.AuthorityRelation))
                g.add((auth_rel, SBM.authority, URIRef(authority)))
                g.add((auth_rel, SBM.relationType, SBM.Object))
                g.add((auth_rel, SBM.authorityCount, Literal(count, datatype=XSD.long)))
                g.add((partition, SBM.authorityRelation, auth_rel))
                added_count += 1

    print(f"Created {created_partitions} new propertyPartitions")
    print(f"Added void:triples to {added_partition_triple_counts} propertyPartitions")
    print(f"Added {added_count} authorityRelation entries")
    print(f"Skipped {skipped_predicates} predicates with no new metadata to add")
    
    print(f"Saving updated TTL to: {output_file}")
    try:
        g.serialize(destination=output_file, format="turtle")
        print("Done!")
        return True
    except Exception as e:
        print(f"Error writing TTL file: {e}")
        return False


if __name__ == "__main__":
    args = parse_args()

    if args.ttl_dir is not None:
        success = update_ttl_directory(args.ttl_dir, args.json_dir, args.suffix)
    else:
        ttl_file = Path(args.ttl_file)
        json_file = Path(args.json_mapping_file)
        output_file = Path(args.output_file) if args.output_file else None
        success = update_ttl_file(ttl_file, json_file, output_file)

    sys.exit(0 if success else 1)
